/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "PapTools - Documentação Claro",
  "tagline": "Orquestração de Processos Inteligente",
  "url": "https://paptools.claro.com.br",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "onBrokenAnchors": "throw",
  "favicon": "img/favicon.png",
  "organizationName": "paptools",
  "projectName": "paptools-documentation",
  "headTags": [
    {
      "tagName": "link",
      "attributes": {
        "rel": "preload",
        "href": "https://paptools.vercel.app/",
        "as": "document"
      }
    }
  ],
  "clientModules": [
    "./src/client/remote-amplitude-analytics.js"
  ],
  "themeConfig": {
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "metadata": [
      {
        "name": "robots",
        "content": "follow, index"
      }
    ],
    "image": "/img/assets/open-graph-shiny.png",
    "prism": {
      "additionalLanguages": [
        "java",
        "ruby",
        "php",
        "csharp",
        "toml",
        "bash",
        "docker"
      ],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": true
      },
      "versionPersistence": "localStorage"
    },
    "navbar": {
      "hideOnScroll": false,
      "logo": {
        "alt": "PAP TOOLS logo",
        "src": "img/assets/logo.png",
        "srcDark": "img/assets/logo_horiz_dark.png",
        "href": "/"
      },
      "items": [
        {
          "label": "Início",
          "to": "/",
          "position": "left",
          "activeBasePath": "none"
        }
      ]
    },
    "footer": {
      "logo": {
        "alt": "PapTools",
        "src": "img/favicon.png",
        "href": "https://claro.com.br",
        "width": 32
      },
      "copyright": "Todos os direitos reservados. © 2025 RedeInova Tecnologia. ",
      "links": [],
      "style": "light"
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "sidebarPath": "C:\\Users\\nicholas.souza\\Documents\\Pap\\sidebars.js",
          "routeBasePath": "/",
          "exclude": [
            "**/clusters/**",
            "**/ai-cookbook/**"
          ],
          "editUrl": "https://github.com/nicholasnasc/documentation/edit/main/docs/",
          "showLastUpdateAuthor": false,
          "showLastUpdateTime": false,
          "includeCurrentVersion": true,
          "admonitions": {
            "keywords": [
              "note",
              "tip",
              "info",
              "caution",
              "danger",
              "competency",
              "copycode"
            ]
          },
          "remarkPlugins": [
            null
          ],
          "rehypePlugins": [
            null
          ]
        },
        "theme": {
          "customCss": "C:\\Users\\nicholas.souza\\Documents\\Pap\\src\\css\\custom.css"
        },
        "sitemap": {
          "changefreq": "daily",
          "priority": 0.5,
          "filename": "sitemap.xml"
        }
      }
    ]
  ],
  "scripts": [
    {
      "src": "/scripts/googletag.js",
      "async": true,
      "defer": true
    },
    {
      "src": "/scripts/copycode-notice.js",
      "async": true,
      "defer": true
    }
  ],
  "stylesheets": [
    {
      "href": "https://cdn.jsdelivr.net/npm/katex@0.13.24/dist/katex.min.css",
      "type": "text/css",
      "integrity": "sha384-odtC+0UGzzFL/6PNoE8rX/SPcQDXBJ+uRepguP4QkPCm2LBxH3FA3y+fKSiJ+AmM",
      "crossorigin": "anonymous"
    }
  ],
  "plugins": [
    null,
    null,
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "ai-cookbook",
        "path": "ai-cookbook",
        "routeBasePath": "ai-cookbook",
        "sidebarPath": false,
        "showLastUpdateAuthor": true,
        "showLastUpdateTime": true,
        "docItemComponent": "@site/src/components/CookbookDocItem",
        "docCategoryGeneratedIndexComponent": "@site/src/components/CookbookCategoryIndex"
      }
    ],
    [
      "C:\\Users\\nicholas.souza\\Documents\\Pap\\plugins\\cookbook-index.js",
      {
        "docsDir": "ai-cookbook",
        "routeBasePath": "ai-cookbook"
      }
    ],
    [
      "C:\\Users\\nicholas.souza\\Documents\\Pap\\node_modules\\@easyops-cn\\docusaurus-search-local\\dist\\server\\server\\index.js",
      {
        "hashed": true,
        "language": [
          "pt",
          "en"
        ],
        "indexDocs": true,
        "indexBlog": false,
        "indexPages": true,
        "docsRouteBasePath": "/",
        "highlightSearchTermsOnTargetPage": true,
        "searchResultLimits": 8,
        "searchResultContextMaxLength": 50,
        "explicitSearchResultPath": true
      }
    ]
  ],
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  }
};
